trigger:
- release/*
pr: none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x86|x64|ARM64'
  buildConfiguration: 'Release'
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'
  appxmanifest: '**/*.appxmanifest'
  versionNumber: 'Set dynamically below in a task'
  
name: $(GITVERSION_AssemblySemFileVer)

steps:

- task: gitversion/setup@0
  inputs:
    versionSpec: '5.x'

- task: gitversion/execute@0

- task: NuGetToolInstaller@1

# - task: NuGetCommand@2
#   inputs:
#     command: 'custom'
#     arguments: 'restore d:\a\1\s\Yugen.Mosaic.Uwp.sln -source "https://api.nuget.org/v3/index.json;https://www.myget.org/F/sixlabors/api/v3/index.json'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VersionAPPX@2
  inputs:
    VersionNumber: '$(GitVersion.AssemblySemFileVer)'

- task: VSBuild@1
  inputs:
    platform: 'x86'
    solution: '$(solution)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:AppxBundlePlatforms="$(buildPlatform)" 
                  /p:AppxPackageDir="$(appxPackageDir)" 
                  /p:AppxBundle=Always 
                  /p:UapAppxPackageBuildMode=StoreUpload 
                  /p:AppxPackageSigningEnabled=false'
    maximumCpuCount: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\AppxPackages'
    ArtifactName: 'drop'